export type PropertyEnrichmentPatch = {
  description?: string | null;
  surface?: number | null;
  landSurface?: number | null;
  rooms?: number | null;
  bedrooms?: number | null;
  latitude?: number | null;
  longitude?: number | null;
  imageUrl?: string | null;
  dpeClass?: string | null;
  gesClass?: string | null;
  dpeConsumptionKwhM2?: number | null;
  gesEmissionKgM2?: number | null;
  bathrooms?: number | null;
  constructionYear?: number | null;
  heating?: string | null;
  orientation?: string | null;
  propertyCondition?: string | null;
  parkingSpaces?: number | null;
  highlights?: string[] | null;
};
