/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as HelpRouteImport } from './routes/help'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as DislikesRouteImport } from './routes/dislikes'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const DislikesRoute = DislikesRouteImport.update({
  id: '/dislikes',
  path: '/dislikes',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/dislikes': typeof DislikesRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/stats': typeof StatsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/dislikes': typeof DislikesRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/stats': typeof StatsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings': typeof ListingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/browse': typeof BrowseRoute
  '/dislikes': typeof DislikesRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/stats': typeof StatsRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/browse'
    | '/dislikes'
    | '/favorites'
    | '/help'
    | '/stats'
    | '/listings/$id'
    | '/listings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/browse'
    | '/dislikes'
    | '/favorites'
    | '/help'
    | '/stats'
    | '/listings/$id'
    | '/listings'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/browse'
    | '/dislikes'
    | '/favorites'
    | '/help'
    | '/stats'
    | '/listings/$id'
    | '/listings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrowseRoute: typeof BrowseRoute
  DislikesRoute: typeof DislikesRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  StatsRoute: typeof StatsRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dislikes': {
      id: '/dislikes'
      path: '/dislikes'
      fullPath: '/dislikes'
      preLoaderRoute: typeof DislikesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrowseRoute: BrowseRoute,
  DislikesRoute: DislikesRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  StatsRoute: StatsRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
